## Numpy

Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

In [1]:
import numpy as np

In [2]:
my_lst=[1,2,3,45,6]

arr=np.array(my_lst)

type(arr)

numpy.ndarray

In [5]:
print(arr) ## one dimensional array

[ 1  2  3 45  6]


In [7]:
## how many elements in a array
arr.shape

(5,)

In [8]:
## Multi-dimensional array 
my_lst1=[1,2,3,4]
my_lst2=[13,23,3,4]
my_lst3=[15,23,3,4]

arr1=np.array([my_lst1,my_lst2,my_lst3])

In [9]:
arr1

array([[ 1,  2,  3,  4],
       [13, 23,  3,  4],
       [15, 23,  3,  4]])

In [10]:
arr1.shape

(3, 4)

In [11]:
## now reshape the array 
arr1.reshape(4,3)

array([[ 1,  2,  3],
       [ 4, 13, 23],
       [ 3,  4, 15],
       [23,  3,  4]])

In [ ]:
arr1.reshape(2,2) ## not reshape

ValueError: cannot reshape array of size 12 into shape (2,2)

In [16]:
arr1.reshape(1,12)

array([[ 1,  2,  3,  4, 13, 23,  3,  4, 15, 23,  3,  4]])

## Indexing

In [19]:
## acessing the elements 
arr=np.array([1,2,3,4,5,6,7,8])

In [21]:
print(arr[3])

4


In [24]:
arr1

array([[ 1,  2,  3,  4],
       [13, 23,  3,  4],
       [15, 23,  3,  4]])

In [50]:
arr1=np.arange(0,17)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [46]:
arr1[1:,2:]

array([[3, 4],
       [3, 4]])

In [42]:
##arr[row,coloumn]
#arr[from row:to row,from coloumn: coloumn] 
arr1[0:3,0:3]

 #arr1[1:3,0:3]

array([[ 1,  2,  3],
       [13, 23,  3],
       [15, 23,  3]])

In [39]:
arr1[1:,1:3]

array([[23,  3],
       [23,  3]])

In [40]:
arr1[1:3,1]

array([23, 23])

In [54]:
np.linspace(1,10,40)

array([ 1.        ,  1.23076923,  1.46153846,  1.69230769,  1.92307692,
        2.15384615,  2.38461538,  2.61538462,  2.84615385,  3.07692308,
        3.30769231,  3.53846154,  3.76923077,  4.        ,  4.23076923,
        4.46153846,  4.69230769,  4.92307692,  5.15384615,  5.38461538,
        5.61538462,  5.84615385,  6.07692308,  6.30769231,  6.53846154,
        6.76923077,  7.        ,  7.23076923,  7.46153846,  7.69230769,
        7.92307692,  8.15384615,  8.38461538,  8.61538462,  8.84615385,
        9.07692308,  9.30769231,  9.53846154,  9.76923077, 10.        ])

In [61]:
## copy function or broadcasting 
arr1.reshape(17,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

In [ ]:
arr1[1:5]=100
arr1 

array([  0, 100, 100, 100, 100,   1,   1,   1,   1,   1,   1,   1,   1,
         1,   1,   1,   1])

#### Math operations 

In [69]:
import numpy as np
 
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
 
# Addition of two Arrays
Sum = np.add(arr1, arr2)
print(Sum)
 
# Addition of all Array elements
Sum1 = np.sum(arr1)
print(Sum1)
 
# Square root of Array
Sqrt = np.sqrt(arr1)
print(Sqrt)
 
# Transpose of Array
Trans_arr = arr1.T
print(Trans_arr)

[[ 7. 13.]
 [ 4. 14.]]
19.0
[[2.         2.64575131]
 [1.41421356 2.44948974]]
[[4. 2.]
 [7. 6.]]
