<a href="https://colab.research.google.com/github/Riyajha182005/Genai-from-scratch/blob/main/7.Numpy/NumpyLearnMore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Basic Array Creation**



In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
## Lets create a list first
a = [1,2,3,4.7,"Riiya"]

In [ ]:
np.array(a) ## See here we have diffrent datatypes and numpy convert all the elements in single datatype "string "

array(['1', '2', '3', '4.7', 'Riiya'], dtype='<U32')

Vectors: 1-Dimensional space

Matrix: 2-Dimensional space  

In [ ]:
## Now see the diffrences and magic in list and numpy
l=[[1,2,3,4],[5,6,7,8]]
l
##Here in the output we can clearly see that output on 1-D

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [ ]:
# Now create the numpy array for the same list l
np.array(l)
## see the output in 2-dimensional space

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

**Array Generation Function**

In [ ]:
arr1 =np.arange(1,12)

In [ ]:
arr2=np.zeros((2,3)) #2*3 matrix
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
## lets Explore more inbuilt function
##linspace
np.linspace(1,10,4)


array([ 1.,  4.,  7., 10.])

**Random Generation Function**

In [ ]:
np.random.rand(10)

array([0.94849099, 0.9650275 , 0.55567932, 0.95685314, 0.82757109,
       0.40746809, 0.79009406, 0.31717874, 0.45605772, 0.0297677 ])

In [ ]:
np.random.randn(10)

array([-1.04544636,  0.6665637 ,  1.87670669, -2.04312672,  0.00702467,
        1.34413157,  0.88943312,  1.56601655, -0.93297688, -0.14795515])

In [ ]:
np.random.randint(1,100,10)

array([ 8, 87, 50, 48, 52, 64, 55, 30, 61, 69])

**Array Attributes**

In [ ]:
arr2.shape## (row,coloumn)

(2, 3)

In [ ]:
arr2.size

6

In [ ]:
arr2.dtype

dtype('float64')

**Array Methods**

In [ ]:
arr2.min()

np.float64(0.0)

In [ ]:
arr2.sum()

np.float64(0.0)

In [ ]:
arr3=np.ones([3,3])
arr3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.sum(arr3,axis=0) ## column

array([3., 3., 3.])

In [ ]:
arr4=np.array([[1,23,34],[34,45,67],[90,78,67]])
arr4

array([[ 1, 23, 34],
       [34, 45, 67],
       [90, 78, 67]])

In [ ]:
np.sum(arr4,axis=1) ##row

array([ 58, 146, 235])

In [ ]:
arr4.argmax()

np.int64(6)

In [ ]:
arr4.argmin()

np.int64(0)

In [ ]:
arr4.mean()

np.float64(48.77777777777778)

In [ ]:
arr4.std()

np.float64(27.112021842626596)

**Reshaping And Resizing**

In [ ]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

**Numpy indexing**

In [ ]:
arr6=np.arange(21,31)
arr6

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
print (arr6[5])

26


**Slicing**

In [ ]:
arr6[2:8]

array([23, 24, 25, 26, 27, 28])

In [ ]:
arr6[8:]

array([29, 30])

In [ ]:
arr6[4::2] ## steps in third column

array([25, 27, 29])

In [ ]:
arr6[:8]

array([21, 22, 23, 24, 25, 26, 27, 28])

**Numpy Slicing and Indexing of Matrix**

In [ ]:
arr_new=np.arange(1,31).reshape(6,5)
arr_new

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr_new[0,3] ## slicing out elements

np.int64(4)

In [ ]:
arr_new[3:,3:] ## slicing out rows and column

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
arr_new[:,3] ## Slicing out coloumn

array([ 4,  9, 14, 19, 24, 29])

**Boolean Indexing**

In [ ]:
bool_index =  arr_new%2 ==0
bool_index

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [ ]:
arr_new = arr_new[bool_index]
arr_new

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

**Array Operations**

*Arithmetic Opertaion*

In [ ]:
a1=np.array([1,2,3,4,5,6])
a2=np.array([4,5,5,6,6,43])

In [ ]:
a3=a1+a2

In [ ]:
print(a3)

[ 5  7  8 10 11 49]


In [ ]:
a4=a1*a2

In [ ]:
print(a4)

[  4  10  15  24  30 258]


In [ ]:
print(a1**a2)

[                   1                   32                  243
                 4096                15625 -1451328960385253376]


**Broadcasting**

In [ ]:
## if we have multiple elements and add single elemnet to every element
## in array we dont need any loop to iterate the elements
l=[10,23,456,67]
ar1=np.array(l)

In [ ]:
print(ar1+10)

[ 20  33 466  77]


We can also manipulate the matrices

In [ ]:
## Let see example
mat1=np.arange(1,37).reshape(9,4)
mat1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36]])

In [ ]:
mat1+10 ## see the magiic of inbuilt library , okay not the magic

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30],
       [31, 32, 33, 34],
       [35, 36, 37, 38],
       [39, 40, 41, 42],
       [43, 44, 45, 46]])

**Matrix Operation**

In [2]:
mat1=np.arange(1,25).reshape(6,4)

In [5]:
mat2=np.arange(25,49).reshape(4,6)

In [6]:
np.dot(mat1,mat2) ## Multiplication of matrix

array([[ 370,  380,  390,  400,  410,  420],
       [ 914,  940,  966,  992, 1018, 1044],
       [1458, 1500, 1542, 1584, 1626, 1668],
       [2002, 2060, 2118, 2176, 2234, 2292],
       [2546, 2620, 2694, 2768, 2842, 2916],
       [3090, 3180, 3270, 3360, 3450, 3540]])

In [7]:
mat1.T ## Transpose of the matrix

array([[ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23],
       [ 4,  8, 12, 16, 20, 24]])

**Stacking Array**

In [10]:
ex1=np.array([12,13,24,23])
exr2=np.array([12,13,24,23])

In [11]:
np.vstack((ex1,exr2))

array([[12, 13, 24, 23],
       [12, 13, 24, 23]])

In [12]:
np.column_stack((ex1,exr2))

array([[12, 12],
       [13, 13],
       [24, 24],
       [23, 23]])

In [14]:
np.hstack((ex1,exr2))

array([12, 13, 24, 23, 12, 13, 24, 23])

**Splitting the array**

In [16]:
np.hsplit(mat1,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [17]:
np.vsplit(mat1,2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [19]:
np.vsplit(mat1,3)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]])]